apiVersion: v1 
kind: Service 
metadata: 
  name: mongo-service 
spec: 
  selector: 
    app: mongo 
  ports: 
    - protocol: TCP 
      port: 27017 
      targetPort: 27017 
---
apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: mongo 
spec: 
  serviceName: "mongo-service" 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo 
  template: 
    metadata: 
      labels: 
        app: mongo 
    spec: 
      containers: 
        - name: mongo 
          image: mongo:latest 
          resources: 
            requests: 
              memory: 128Mi 
              cpu: 100m 
            limits: 
              memory: 256Mi 
              cpu: 200m 
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME 
              valueFrom: 
                secretKeyRef: 
                  name: mongo-credentials 
                  key: username 
            - name: MONGO_INITDB_ROOT_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mongo-credentials 
                  key: password 
          ports: 
            - containerPort: 27017 
          volumeMounts: 
            - name: mongo-persistent-storage 
              mountPath: /data/db 
            - name: init-script 
              mountPath: /docker-entrypoint-initdb.d/init.js 
              subPath: init.js 
      volumes: 
        - name: mongo-persistent-storage 
          persistentVolumeClaim: 
            claimName: mongo-persistent-storage 
        - name: init-script 
          configMap: 
            name: mongo-init-script 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mongo-persistent-storage 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 200Mi 
