apiVersion: v1 
kind: Service 
metadata: 
  name: nginx 
  namespace: argocd-demo 
spec: 
  selector: 
    app: nginx 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 80
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment 
  namespace: argocd-demo 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
        - name: nginx-container 
          image: nginx:1.14.2
          resources: 
            requests: 
              memory: 128Mi 
              cpu: 100m 
            limits: 
              memory: 256Mi 
              cpu: 200m 
          ports: 
            - containerPort: 80